# Generated by Django 5.2.16 on 2026-07-30.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_data(apps, schema_editor):
    ForbiddenRule = apps.get_model("core", "ForbiddenRule")
    RulePattern = apps.get_model("core", "RulePattern")
    MiniAppPolicy = apps.get_model("core", "MiniAppPolicy")
    HistoryScan = apps.get_model("core", "HistoryScan")
    RulePattern.objects.bulk_create(
        [
            RulePattern(
                rule_id=rule.pk,
                encrypted_phrase=rule.encrypted_phrase,
                phrase_fingerprint=rule.phrase_fingerprint,
            )
            for rule in ForbiddenRule.objects.all()
        ],
        ignore_conflicts=True,
    )
    MiniAppPolicy.objects.filter(notify_admin=True).update(notify_operator=True)
    HistoryScan.objects.filter(status="awaiting_confirmation").update(
        status="cancelled",
        cancel_requested=True,
        last_error_code="legacy_preview_retired",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_history_scan_and_removal_cancellation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("menu_detected", "Mini App обнаружено в меню"), ("outgoing_detected", "Исходящее сообщение обнаружено"), ("menu_disabled", "Mini App отключено в меню"), ("bot_blocked", "Бот заблокирован"), ("message_deleted", "Сообщение удалено"), ("user_warned", "Пользователь предупреждён"), ("admin_notified", "Администратор уведомлён")], max_length=32)),
                ("bot_id", models.BigIntegerField(blank=True, null=True)),
                ("bot_username", models.CharField(blank=True, max_length=64)),
                ("result", models.CharField(choices=[("observed", "Обнаружено"), ("warned", "Предупреждено"), ("succeeded", "Выполнено"), ("failed", "Ошибка"), ("skipped", "Пропущено")], max_length=16)),
                ("dedup_key", models.CharField(max_length=64)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("repeat_count", models.PositiveIntegerField(default=1)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-last_seen_at"]},
        ),
        migrations.CreateModel(
            name="RuleChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("encrypted_payload", models.TextField()),
                ("change_summary", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Ожидает"), ("approved", "Одобрен"), ("rejected", "Отклонён"), ("cancelled", "Отменён пользователем")], default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RuleDialogScope",
            fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"))],
        ),
        migrations.CreateModel(
            name="RulePattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("encrypted_phrase", models.TextField()),
                ("phrase_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="TelegramDialog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("peer_fingerprint", models.CharField(max_length=64)),
                ("encrypted_label", models.TextField()),
                ("kind", models.CharField(choices=[("saved", "Избранное"), ("private", "Личный чат"), ("group", "Группа"), ("supergroup", "Супергруппа"), ("channel", "Канал")], max_length=16)),
                ("available", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["kind", "id"]},
        ),
        migrations.RemoveConstraint(model_name="historyscan", name="unique_active_history_scan"),
        migrations.AddField(model_name="forbiddenrule", name="encrypted_label", field=models.TextField(blank=True)),
        migrations.AddField(model_name="forbiddenrule", name="revision", field=models.PositiveIntegerField(default=1)),
        migrations.AddField(model_name="historyscan", name="rule", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="history_scans", to="core.forbiddenrule")),
        migrations.AddField(model_name="historyscan", name="rule_revision", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="miniapppolicy", name="notify_operator", field=models.BooleanField(default=False)),
        migrations.AddConstraint(model_name="historyscan", constraint=models.UniqueConstraint(condition=models.Q(("status", "running")), fields=("account",), name="unique_running_history_scan")),
        migrations.AddField(model_name="operatornotification", name="account", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operator_notifications", to="core.telegramaccount")),
        migrations.AddField(model_name="operatornotification", name="processed_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="operatornotification", name="rule", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="core.miniapprule")),
        migrations.AddField(model_name="rulechangerequest", name="resolved_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="rulechangerequest", name="rule", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="change_requests", to="core.forbiddenrule")),
        migrations.AddField(model_name="rulechangerequest", name="user", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rule_change_requests", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="ruledialogscope", name="rule", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dialog_scopes", to="core.forbiddenrule")),
        migrations.AddField(model_name="rulepattern", name="rule", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="patterns", to="core.forbiddenrule")),
        migrations.AddField(model_name="telegramdialog", name="account", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dialogs", to="core.telegramaccount")),
        migrations.AddField(model_name="ruledialogscope", name="dialog", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rule_scopes", to="core.telegramdialog")),
        migrations.AddConstraint(model_name="operatornotification", constraint=models.UniqueConstraint(condition=models.Q(("processed_at__isnull", True)), fields=("dedup_key",), name="unique_open_operator_notification")),
        migrations.AddConstraint(model_name="rulechangerequest", constraint=models.UniqueConstraint(condition=models.Q(("status", "pending")), fields=("rule",), name="unique_pending_rule_change")),
        migrations.AddConstraint(model_name="rulepattern", constraint=models.UniqueConstraint(fields=("rule", "phrase_fingerprint"), name="unique_rule_pattern")),
        migrations.AddConstraint(model_name="telegramdialog", constraint=models.UniqueConstraint(fields=("account", "peer_fingerprint"), name="unique_account_dialog")),
        migrations.AddConstraint(model_name="ruledialogscope", constraint=models.UniqueConstraint(fields=("rule", "dialog"), name="unique_rule_dialog_scope")),
        migrations.RunPython(migrate_existing_data, migrations.RunPython.noop),
    ]
